before_script:
  - echo "BRANCH='${CI_COMMIT_REF_NAME}'\n" >> sh2msg/cli/version.py
  - echo "COMMIT_REF='${CI_COMMIT_SHA:0:8}'\n" >> sh2msg/cli/version.py


linux-amd64:
  stage: build
  image: python:3.7.1-stretch
  artifacts:
    name: "${CI_PROJECT_NAME}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA:0:8}-linux-amd64"
    paths:
      - sh2msg-linux-amd64/*
  script:
    - pip3 install pyinstaller -q
    - pyinstaller sh2msg.spec
    - cp README.md dist/
    - cp COPYING dist/
    - mv dist sh2msg-linux-amd64

sh2msg-win-amd64:
  image: debian:stable
  stage: build
  artifacts:
    name: "${CI_PROJECT_NAME}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA:0:8}-windows-i386"
    paths:
      - sh2msg-win-amd64/*
  script:
    - apt-get update -y
    - dpkg --add-architecture i386
    - apt update
    - apt-get install wine-stable wine32 wget xvfb -y
    - wget https://www.python.org/ftp/python/3.7.4/python-3.7.4-amd64.exe
    - wineboot -u
    - wget https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks
    - chmod +x winetricks
    - sh winetricks win7
    - xvfb-run wine python-3.7.4-amd64.exe /quiet InstallAllUsers=1 PrependPath=1 Include_test=0 TargetDir=c:\Python374
    - wine C:/Python374/python.exe -m ensurepip --upgrade
    - wine C:/Python374/python.exe -m pip install pyinstaller
    - wine C:/Python374/scripts/pyinstaller.exe sh2msg.spec
    - cp README.md dist/
    - cp COPYING dist/
    - mv dist sh2msg-win-amd64
